---
# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Chris-Prime/FactionsPE
branches:
- reborn
projects:
  FactionsPE:
    path: ""
    libs:
     - local: Localizer
     - local: Economizer
     - local: Dominate
     - local: Simple-LibLoader
  Localizer:
    path: lib/Localizer
    type: library
  Economizer:
    path: lib/Economizer
    type: library
  Dominate:
    path: lib/Dominate
    type: library
  Simple-LibLoader:
    path: src/sll
    type: library
...
