---
# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Chris-Prime/FactionsPE
branches:
- reborn
projects:
  FactionsPE:
    path: ""
    libs:
     - local: lib/Localizer
     - local: lib/Economizer
     - local: lib/Dominate
     - local: src/sll
...
