---
language: 'lv'

formats:
 nametag: "[{RANK}{FACTION}] {PLAYER}"
 chat:
  normal: "[{RANK}{FACTION}] {PLAYER}: {MESSAGE}"
  faction: "&7F>>&f [{RANK}{FACTION}] {PLAYER}: {MESSAGE}"
 rank:
  leader: "**"
  officer: "*"
  member: "+"
  recruit: "-"

# Optional functions
enable-hud: false
enable-stats: false

prices:
 faction:
  create: 3500

data-provider: json
mysql-settings:
 host: db4free.net
 user: chris_prime
 password: factionspe
 database: factionspe
 port: 3306

# Settings below affects gameplay the most, not as settings above, they configure plugin meta data
Settings:
 canJoinWithNegativePowerLevel: false
 canLeaveWithNegativePowerLevel: false
 homesEnabled: true
 homesTeleportToOnDeathActive: true
 homesTeleportCommandEnabled: true
 homesTeleportAllowedFromEnemyTerritory: false
 homesTeleportAllowedFromDifferentWorld: true
 homesTeleportAllowedEnemyDistance: 10
 worldsPvpRulesEnabled: [world]
 playersWhoBypassAllProtection: []
 actionDeniedPainAmount: 1
 worldsPowerLossEnabled: [world]
 worldsClaimingEnabled: [world]
 showMotdOnJoin: true
 protectionLiquidFlowEnabled: true
 materialsEditOnInteract: []
 materialsContainer: []
 materialsDoors: []
 materialsEditTools: []
 materialsEditToolsDupeBug: []
 claimingFromOthersAllowed: true
 claimsCanBeUnconnectedIfOwnedByOtherFaction: false
 claimsCanBeUnconnectedIfOwnedByOtherFaction: false
 claimsMustBeConnected: true
 claimMinimumChunksDistanceToOthers: 1
 claimedLandsMax: 9999
 claimsRequireMinFactionMembers: 1
 disablePVPForFactionlessPlayers: true
 enablePVPAgainstFactionlessInAttackersLand: true
 enablePVPBetweenFactionlessPlayers: true
 logFactionDisband: true
 defaultPlayerPower: 10
 factionMemberLimit: 10
 power:
  max: 10
  updateInterval: 600
  perHour: 1
  perDeath: -2
 invitation.expire.time: 60

...
