---
language: 'en'

formats:
 nametag: "[{RANK}{FACTION}] {PLAYER}"
 chat:
  normal: "[{RANK}{FACTION}] {PLAYER}: {MESSAGE}"
  faction: "&7F>>&f [{RANK}{FACTION}] {PLAYER}: {MESSAGE}"
 rank:
  leader: "**"
  officer: "*"
  member: "+"
  recruit: "-"

# Optional functions
enable-hud: false
enable-stats: false

prices:
 faction:
  create: 3500

data-provider: json
mysql-settings:
 host: db4free.net
 user: chris_prime
 password: factionspe
 database: factionspe
 port: 3306
...
