---
#
#   FactionsPE: PocketMine-MP Plugin
#   Copyright (C) 2016  Chris Prime
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Plugin language
language: en

# Economy
economy-support: false
economy-plugin: "EconomyAPI"

# Data provider settings
# Supported types as of now: yaml, json
data-provider:
  type: "YAML"
  mysql:
    host: 127.0.0.1
    user: guest
    password: secret
    database: factions-pe

# Chat
# Set this to false if you want to use PureChat
# Although this might not make trouble, but let's save computer resources. Shall we?
chat-formatter: true

# gameplay settings
gameplay:
  log:
    faction-disband: true
    faction-new-leader: true
    faction-creation: true
    member-leave: true
    member-join: true
    member-kick: true
    override: true
  power:
    player:
      max: 10
      min: -10
  faction:
    destroy-empty-factions: true
    member-limit: 10
    disable-permanent-leader-promotion: true
  faction-name:
    max-length: 12
    min-length: 3
  price:
    faction-creation: 5000
  homes-must-be-in-claimed-territories: true
  can-leave-with-negative-power: false
  can-join-with-negative-power: false
  chat:
    player: "{NAME}: {MESSAGE}"
    member: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white> {NAME}: {MESSAGE}"
    member-title: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white>[{TITLE}]<white> {NAME}: {MESSAGE}"
    faction-chat: "<gold>{BADGE}<gray>{NAME}<white>:<gray> {MESSAGE}"
    badge:
      leader: "^"
      officer: "**"
      member: "*"
      recruit: "-"
  worlds-pvp-rules-enabled: [world]
  disable-pvp-for-factionless-players: true
  enable-pvp-against-factionless-in-attackers-land: true
  enable-pvp-between-factionless-players: true
...
