---
#
#   FactionsPE: PocketMine-MP Plugin
#   Copyright (C) 2016  Chris Prime
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Plugin language
language: en

# Economy
economy-support: false
economy-plugin: "EconomyAPI"

# Data provider settings
# Supported types as of now: yaml, json, mysql
data-provider:
  type: "mysql"
  mysql:
    host: 127.0.0.1
    user: guest
    password: secret
    database: factions-pe

# Chat
# Set this to false if you want to use PureChat
chat-formatter: true

mysql:
 host: 127.0.0.1
 user: root
 database: fpe
 password: ChrisIsCool
 port: 3306

# gameplay settings
gameplay:
  log:
    faction-disband: true
    faction-new-leader: true
    faction-creation: true
    member-leave: true
    member-join: true
    member-kick: true
    override: true
    faction-chat: true
    perm-change: true
  power:
    player:
      max: 100
      min: -100
      per-death: 5
      per-claim: 5
      per-update: 1
      default: 10
    update-every: 10
    update-enabled: true
  faction:
    destroy-empty-factions: true
    member-limit: 10
    disable-permanent-leader-promotion: true
  faction-name:
    max-length: 12
    min-length: 3
  price:
    faction-creation: 5000
  home:
    enabled: true
    teleport-to-on-death: true
    teleport-command-enabled: true
    must-be-in-claimed-territories: true
    teleport-allowed-from-enemy-territory: false
    home.teleport-allowed-from-different-world: true
    homes.teleport-allowed-enemy-distance: 10
    teleport-ignore-enemies-if-in-own-territory: false
  can-leave-with-negative-power: false
  can-join-with-negative-power: false
  chat:
    player: "{NAME}: {MESSAGE}"
    member: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white> {NAME}: {MESSAGE}"
    member-title: "<gray>[<gold>{BADGE}<white>{FACTION}<gray>]<white>[{TITLE}]<white> {NAME}: {MESSAGE}"
    faction-chat: "<gold>{BADGE}<white>{NAME}<white><gray>>><white> {MESSAGE}"
    badge:
      leader: "**"
      officer: "*"
      member: "+"
      recruit: "-"
  color:
    enemy: "<red>"
    ally: "<green>"
    truce: "<gold>"
    neutral: "<white>"
  worlds-pvp-rules-enabled: []
  worlds-claiming-enabled: [world]
  worlds-power-loss-enabled: [world]
  players-who-bypass-all-protection: []
  disable-pvp-for-factionless-players: true
  enable-pvp-against-factionless-in-attackers-land: true
  enable-pvp-between-factionless-players: true
  enable-pvp-for-factionless-players: true
  set-radius-max: 5
  handle-exploit-tnt-water-log: true
  show-motd-on-join: true
  claims-require-min-faction-members: 1
  claimed-lands-max: 99999999
  claims-must-be-connected: true
  claims-can-be-unconnected-if-owned-by-other-faction: true
  claiming-from-others-allowed: true
  action-denied-pain-amount: 1
  protection-liquid-flow-enabled: true
  materials-edit-on-interact: []
  materials-container: []
  materials-doors: []
  materials-edit-tools: []
  materials-edit-tools-dupe-bug: []
  send-plot-faction-description: true
...
